version: "3.7"


services:
  kamodo-dask:
    image: kamodo/dask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  dev: # developer notebook to test microservice with db
    ports:
      - 8888:8888
    depends_on:
      - scheduler
    image: kamodo/daskdev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/code
    container_name: kamodo-dask-dev
    environment:
      SCHEDULER_HOST: tcp://scheduler:8786
      PARQUET_ENDPOINT: ${PARQUET_ENDPOINT}
      ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
    command:
      - jupyter
      - notebook
      - /code
      - --port=8888
      - --no-browser
      - --ip=0.0.0.0
      - --allow-root
  scheduler:
    image: kamodo/dask
    command: dask scheduler
    ports:
      - 8786:8786 # Scheduler port
      - 8787:8787 # Dashboard port
  worker1:
    image: kamodo/dask
    command: dask worker tcp://scheduler:8786 --no-nanny
    depends_on:
      - scheduler
  worker2:
    image: kamodo/dask
    command: dask worker tcp://scheduler:8786 --no-nanny
    depends_on:
      - scheduler
  worker3:
    image: kamodo/dask
    command: dask worker tcp://scheduler:8786 --no-nanny
    depends_on:
      - scheduler
  worker4:
    image: kamodo/dask
    command: dask worker tcp://scheduler:8786 --no-nanny
    depends_on:
      - scheduler
